# FlexibleUNet model configuration

# Model architecture
_target_: model.SegmentationModel
backbone: "efficientnet-b4"
in_channels: 3
out_channels: 1
pre_trained: true
decoder_channels: [256, 128, 64, 32, 16]
spatial_dimensions: 2

# Loss function
loss:
  _target_: monai.losses.DiceLoss
  sigmoid: true
  smooth_nr: 1e-5
  smooth_dr: 1e-5
  include_background: true
  reduction: "mean"

# Metrics
metrics:
  dice:
    _target_: monai.metrics.DiceMetric
    include_background: true
    reduction: "mean"
    get_not_nans: false
  
  # Additional metrics (optional)
  hausdorff:
    _target_: monai.metrics.HausdorffDistanceMetric
    include_background: true
    reduction: "mean"
    percentile: 95