name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-cache-dir torch==2.0.1+cpu torchvision==0.15.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
        pip install --no-cache-dir pytest pytest-cov
        pip install --no-cache-dir monai opencv-python-headless
        pip install --no-cache-dir pytorch-lightning hydra-core
        pip install --no-cache-dir -r requirements.txt
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "=== Testing imports ==="
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import monai; print('MONAI:', monai.__version__)"
        python -c "import cv2; print('OpenCV:', cv2.__version__)"
        python -c "import pytorch_lightning as pl; print('Lightning:', pl.__version__)"
        echo "\n=== Running tests ==="
        python -m pytest tests/ -v --disable-warnings

  build-and-test-apps:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install torch==2.0.1+cpu torchvision==0.15.2+cpu torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt --no-cache-dir
    
    - name: Test app imports
      run: |
        python -c "import torch; import monai; import pytorch_lightning; print('✓ Dependencies work')"
        python -c "import app; print('✓ Web app imports work')"
        python -c "import desktop_app; print('✓ Desktop app imports work')"