name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install core dependencies first
          pip install --no-cache-dir torch==2.0.1+cpu torchvision==0.15.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir monai==1.3.0
          pip install --no-cache-dir pytorch-lightning==2.0.1
          pip install --no-cache-dir opencv-python-headless numpy
          pip install --no-cache-dir hydra-core wandb pytest pytest-cov
          # Install project requirements
          pip install --no-cache-dir -e .
      
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          WANDB_MODE: disabled
        run: |
          echo "=== Python Environment ==="
          python --version
          pip list
          
          echo -e "\n=== Testing imports ==="
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import monai; print('MONAI:', monai.__version__)"
          python -c "import pytorch_lightning as pl; print('Lightning:', pl.__version__)"
          python -c "import cv2; print('OpenCV:', cv2.__version__)"
          
          echo -e "\n=== Running tests ==="
          python -m pytest tests/ -v --disable-warnings